#!/usr/bin/env python3
"""Generate PRoot documentation from the single source of truth.

src/cli/proot.h defines everything the command line knows: option
names, value separators, descriptions, details, and the recommended
binding lists used by -R/-S.  This script parses that header and
splices the extracted options into doc/proot.md, producing:

  * MANUAL.md  -- rendered Markdown manual (checked in)
  * proot.1    -- troff man page (checked in)

Both files are regenerated by `make -C doc` and verified by
`make -C doc check`, so the documentation cannot drift away from what
`proot --help` actually prints.
"""

import re
import sys
from pathlib import Path

DOC_DIR = Path(__file__).resolve().parent
CLI_HEADER = DOC_DIR.parent / "src/cli/proot.h"
MANUAL_SRC = DOC_DIR / "proot.md"
MANUAL_OUT = DOC_DIR / "MANUAL.md"
MANPAGE_OUT = DOC_DIR / "proot.1"
OPTIONS_MARKER = "<!--OPTIONS-->"

GENERATED_NOTE = ("<!-- Generated by `make -C doc` from doc/proot.md and "
                  "src/cli/proot.h -- do not edit. -->\n\n")

ESCAPES = {"n": "\n", "t": "\t", "\\": "\\", '"': '"', "'": "'", "0": "\0"}


def unescape_c_string(raw):
    return re.sub(r"\\(.)", lambda m: ESCAPES.get(m.group(1), m.group(1)), raw)


def join_continuations(text):
    """Apply C's backslash-newline line splicing."""
    return re.sub(r"\\\n", "", text)


def c_string(pattern, text):
    m = re.search(pattern + r'\s*=\s*"((?:\\.|[^"])*)"', text)
    return unescape_c_string(m.group(1)) if m else None


def parse_bindings(source, array_name):
    m = re.search(array_name + r"\[\]\s*=\s*\{(.*?)\};", source, re.S)
    if not m:
        sys.exit(f"generate.py: cannot find {array_name} in {CLI_HEADER}")
    body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)  # drop commented items
    items = re.findall(r'"((?:\\.|[^"])*)"', body)
    return [unescape_c_string(i) for i in items]


def parse_options(source):
    """Parse the .options array of proot_cli into a list of dicts."""
    m = re.search(r"\.options\s*=\s*\{(.*?)END_OF_OPTIONS", source, re.S)
    if not m:
        sys.exit(f"generate.py: cannot find .options in {CLI_HEADER}")
    region = m.group(1)

    # Split on preprocessor lines first so each block knows its guard.
    segments = []  # (guard, text)
    guard = None
    buf = ""
    for line in region.splitlines():
        if line.lstrip().startswith("#if"):
            if buf.strip():
                segments.append((guard, buf))
            buf = ""
            guard = line.strip()
        elif line.lstrip().startswith("#endif"):
            if buf.strip():
                segments.append((guard, buf))
            buf = ""
            guard = None
        else:
            buf += line + "\n"
    if buf.strip():
        segments.append((guard, buf))

    options = []
    for guard, seg in segments:
        for block in re.split(r"(?=\{\s*\.class\s*=)", seg):
            if ".class" not in block:
                continue
            opt = {"guard": guard}
            opt["class"] = c_string(r"\.class", block)

            args_m = re.search(
                r"\.arguments\s*=\s*\{(.*?)\{\s*\.name\s*=\s*NULL", block, re.S
            )
            opt["args"] = []
            for am in re.finditer(
                r'\.name\s*=\s*"([^"]*)"\s*,\s*\.separator\s*=\s*'
                r"'((?:\\.|[^'])*)'\s*,\s*\.value\s*=\s*"
                r'(NULL|"((?:\\.|[^"])*)")',
                args_m.group(1),
            ):
                sep = unescape_c_string(am.group(2))
                opt["args"].append(
                    {
                        "name": am.group(1),
                        "separator": None if sep == "\0" else sep,
                        "value": None if am.group(3) == "NULL" else unescape_c_string(am.group(4)),
                    }
                )

            opt["handler"] = re.search(r"\.handler\s*=\s*(\w+)", block).group(1)
            opt["description"] = c_string(r"\.description", block) or ""
            opt["detail"] = c_string(r"\.detail", block) or ""
            options.append(opt)
    return options


def opt_signature(opt):
    """'-r path, --rootfs=path' style signature (plain text markers)."""
    parts = []
    for a in opt["args"]:
        if a["separator"] is None:
            parts.append(a["name"])
        else:
            sep = a["separator"]
            parts.append(a["name"] + (sep if sep != " " else " ") + a["value"])
    return parts


def detail_lines(opt, bindings=None):
    """Yield (kind, text) for an option's .detail field.

    kind is 'para' (paragraph text), 'bullet' (list item) or None for a
    paragraph break.  For -R/-S the bullet list is replaced by the real
    recommended_bindings[]/recommended_su_bindings[] array contents.
    """
    lines = opt["detail"].split("\n")
    out = []
    bullets_dropped = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("* ") or stripped == "*":
            bullets_dropped.append(stripped)
            continue
        if not stripped:
            out.append(None)
        elif stripped.startswith("-"):
            out.append(("para", stripped))
        else:
            out.append(("para", stripped))
    # Trim leading/trailing paragraph breaks.
    while out and out[0] is None:
        out.pop(0)
    while out and out[-1] is None:
        out.pop()
    if bindings:
        out.append(None)
        for b in bindings:
            out.append(("bullet", b))
    else:
        for b in bullets_dropped:
            out.append(("bullet", b[2:] if b.startswith("* ") else b))
    return out


# ---------------------------------------------------------------- Markdown


def md_em(text):
    """Keep *emphasis*, quote `code`.  Input is detail/prose text."""
    return text


def render_options_md(options, bindings_r, bindings_s):
    out = []
    for opt in options:
        heading_parts = ", ".join(f"`{p}`" for p in opt_signature(opt))
        suffix = " *(Android only)*" if opt["guard"] else ""
        out.append(f"#### {heading_parts}{suffix}\n")
        out.append(opt["description"] + "\n")
        binds = bindings_r if opt["handler"] == "handle_option_R" else \
                  bindings_s if opt["handler"] == "handle_option_S" else None
        para = []
        for item in detail_lines(opt, binds) + [None]:
            if item is None:
                if para:
                    out.append(" ".join(para) + "\n")
                    para = []
                continue
            kind, text = item
            if kind == "bullet":
                if para:
                    out.append(" ".join(para) + "\n")
                    para = []
                label = "*path* (the option argument)" if text == "*path*" else f"`{text}`"
                out.append(f"* {label}")
            else:
                para.append(text)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def build_manual_md(options, bindings_r, bindings_s):
    src = MANUAL_SRC.read_text()
    if OPTIONS_MARKER not in src:
        sys.exit(f"generate.py: {OPTIONS_MARKER} missing in {MANUAL_SRC}")
    return GENERATED_NOTE + src.replace(
        OPTIONS_MARKER, render_options_md(options, bindings_r, bindings_s)
    )


# ---------------------------------------------------------------- troff


def m(text):
    """Escape text for troff and apply *emphasis* -> \\fI."""
    text = text.replace("\\", r"\e")
    text = re.sub(r"\*([^*\n]+)\*", r"\\fI\1\\fR", text)
    text = text.replace("-", r"\-")
    text = re.sub(r"^(['.])", r"\\&\1", text)
    return text


def md_inline(text):
    """Markdown inline -> troff for manual body text."""
    text = text.replace("\\", r"\e")
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1 (\\fI\2\\fR)", text)
    text = re.sub(r"`([^`]+)`", r"\\fB\1\\fR", text)
    text = re.sub(r"\*([^*\n]+)\*", r"\\fI\1\\fR", text)
    text = text.replace("-", r"\-")
    text = re.sub(r"^(['.])", r"\\&\1", text)
    return text


def render_options_man(options, bindings_r, bindings_s):
    out = []
    cur_class = None
    for opt in options:
        if opt["class"] != cur_class:
            cur_class = opt["class"]
            out.append(f'.SS "{cur_class}"')
        sig = []
        for a in opt["args"]:
            if a["separator"] is None:
                sig.append(r"\fB" + m(a["name"]) + r"\fR")
            else:
                sep = a["separator"]
                j = "=" if sep == "=" else " "
                sig.append(
                    r"\fB" + m(a["name"]) + r"\fR" + j + r"\fI" + m(a["value"]) + r"\fR"
                )
        line = ", ".join(sig)
        if opt["guard"]:
            line += " (Android only)"
        out.append(".TP")
        out.append(line)
        out.append(m(opt["description"]))
        binds = bindings_r if opt["handler"] == "handle_option_R" else \
                  bindings_s if opt["handler"] == "handle_option_S" else None
        para_open = False
        for item in detail_lines(opt, binds):
            if item is None:
                out.append(".PP")
                para_open = False
                continue
            kind, text = item
            if kind == "bullet":
                if text == "*path*":
                    text = r"\fIpath\fR (the option argument)"
                    out.append(".IP \\[bu] 2")
                    out.append(text)
                else:
                    out.append(".IP \\[bu] 2")
                    out.append(m(text))
                para_open = False
            else:
                if para_open:
                    out[-1] += " " + m(text)
                else:
                    out.append(m(text))
                    para_open = True
        out.append("")
    return "\n".join(out)


def convert_md_to_man(src, options, meta, bindings_r, bindings_s):
    """Very small md subset -> troff, used for the manual's prose."""
    lines = src.splitlines()
    body = []
    in_code = False
    para = []
    section = None
    skip_title_done = False

    in_comment = False

    def flush_para():
        if para:
            body.append(md_inline(" ".join(para)))
            para.clear()

    for line in lines:
        if in_comment:
            if "-->" in line:
                in_comment = False
            continue
        if line.strip() == OPTIONS_MARKER:
            flush_para()
            body.append(render_options_man(options, bindings_r, bindings_s))
            continue
        if line.strip().startswith("<!--"):
            if "-->" not in line:
                in_comment = True
            continue
        if line.startswith("# ") and not skip_title_done:
            skip_title_done = True  # H1 title -> NAME handled separately
            continue
        if line.startswith("## "):
            flush_para()
            section = line[3:].strip()
            body.append(f'.SH "{section.upper()}"')
            continue
        if line.startswith("### "):
            flush_para()
            body.append(f'.SS "{md_inline(line[4:].strip())}"')
            continue
        if line.startswith("    ") and line.strip():
            flush_para()
            if not in_code:
                body.append(".EX")
                in_code = True
            body.append(line[4:].replace("\\", r"\e").replace("-", r"\-"))
            continue
        if in_code:
            body.append(".EE")
            in_code = False
        if not line.strip():
            flush_para()
            continue
        if line.startswith("- "):
            flush_para()
            body.append(".IP \\[bu] 2")
            body.append(md_inline(line[2:].strip()))
            continue
        para.append(line.strip())
    flush_para()
    if in_code:
        body.append(".EE")
    return "\n".join(body) + "\n"


def build_manpage(options, meta, bindings_r, bindings_s):
    src = MANUAL_SRC.read_text()
    header = [
        f'.TH PROOT 1 "" "PRoot {meta["version"]}" "User Commands"',
        '.SH "NAME"',
        f'{meta["name"]} \\- {m(meta["subtitle"])}',
    ]
    return "\n".join(header) + "\n" + convert_md_to_man(
        src, options, meta, bindings_r, bindings_s
    )


# ---------------------------------------------------------------- main


def main():
    source = join_continuations(CLI_HEADER.read_text())
    meta = {
        "version": re.search(r'#define\s+VERSION\s+"([^"]+)"', source).group(1),
        "name": c_string(r"\.name", source),
        "subtitle": c_string(r"\.subtitle", source),
        "colophon": c_string(r"\.colophon", source),
    }
    bindings_r = parse_bindings(source, "recommended_bindings")
    bindings_s = parse_bindings(source, "recommended_su_bindings")
    options = parse_options(source)

    outputs = {
        MANPAGE_OUT: build_manpage(options, meta, bindings_r, bindings_s),
        MANUAL_OUT: build_manual_md(options, bindings_r, bindings_s),
    }

    check = "--check" in sys.argv
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.name)
        else:
            path.write_text(content)
            print(f"generated {path.relative_to(DOC_DIR.parent)}")

    if check:
        if stale:
            print("stale generated docs: " + ", ".join(stale), file=sys.stderr)
            print("run `make -C doc` to regenerate", file=sys.stderr)
            sys.exit(1)
        print("generated docs are up to date")


if __name__ == "__main__":
    main()
